- name: Send PR Review to External App
  env:
    GH_EVENT: ${{ toJSON(github.event) }}
  run: |
    curl -X POST https://hangnail-used-emergency.ngrok-free.dev/api/webhooks/c6ad61a3-6933-4100-a6bb-9c5e254b58be  -H "Content-Type: application/json" -H "X-GitHub-Event: pull_request_review"  -d "$GH_EVENT"
